# Generated by Django 5.0.1 on 2024-01-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caketype', models.CharField(max_length=255)),
                ('cakeevent', models.CharField(max_length=255)),
            ],
        ),
    ]
