# Generated by Django 5.0.1 on 2024-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
