# Generated by Django 5.0.1 on 2024-01-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_cakefinaljson'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakefinaljson',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
