# Generated by Django 5.0.1 on 2024-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_cakefinaljson_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
