# Generated by Django 5.0.1 on 2024-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_cake_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakefinaljson',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
